import Save_import

parameters, _ = Save_import.load_from_checkpoint("./Model/best1LongTest0checkpoint.pth.tar")

print("Parameters :\n")
print("\nnumber of Columns : ", parameters.nColumns)
print("\nnumber of number_classes : ", parameters.number_classes)
print("\nnumber of actual_epoch : ", parameters.actual_epoch)
print("\nnumber of batch_size : ", parameters.batch_size)
print("\nnumber of batch_size_val : ", parameters.batch_size_val)
print("\nnumber of beta1 : ", parameters.beta1)
print("\nnumber of beta2 : ", parameters.beta2)
print("\nnumber of dropFactor : ", parameters.dropFactor)
print("\nnumber of epsilon : ", parameters.epsilon)
print("\nnumber of epoch_total : ", parameters.epoch_total)
print("\nnumber of learning_rate : ", parameters.learning_rate)
print("\nnumber of name_network : ", parameters.name_network)
print("\nnumber of nFeatMaps : ", parameters.nFeatMaps)
print("\nnumber of num_workers : ", parameters.num_workers)
print("\nnumber of weight_decay : ", parameters.weight_decay)
print("\nnumber of size_image_crop : ", parameters.size_image_crop)
print("\nnumber of transforms_output : ", parameters.transforms_output)
print("\nnumber of transforms_input : ", parameters.transforms_input)
print("\nnumber of train_number : ", parameters.train_number)
